### ISSUE TITLE
Regression in 2.1.5: Creation and deletion of activity records

### ISSUE THREAD

**Issue by klasnja** [kpwhri/heartsteps#123] opened 2020-02-03 05:50 UTC
I just noticed a bug in the newly released 2.1.5: when manually creating an activity record, when you tap save, you get the spinner saying that the record is being created, but when it disappears, the form doesn't close. It looks like nothing happened. You have to hit Cancel to get out of the activity creation screen and return to the activity list. I tapped Save a second time, thinking that nothing happened, and when the form still didn't close, I hit Cancel, which returned me to the list view where there were now two copies of the logged bike ride. 

I then tried to delete one, but I get a similar behavior: clicking the Delete button doesn't close the form. One has to hit Cancel to get out, but the activity is not actually deleted. I tried deleting the duplicate several times without success. 

This regression seems to be new. this was working fine in the previous version, I am pretty sure.

**Comment by nickdotreid** [comment] 2020-04-07 17:52
@klasnja is this still an issue? I can't reproduce it.

I'd like to close this issue if you can't reproduce the issue.

**Comment by jup014** [comment] 2021-08-05 00:44
It is not reproduced on my iPhone. I'm closing it but we might want to test it thoroughly later with *potential* testers.

**Closed by jup014** 2021-08-05 00:44 UTC
Labels: bug
